kind: Service
apiVersion: v1
metadata:
  name: devops-nginx-svc
  namespace: ks-devops-test
  labels:
    app: devopstest
    container: devops-nginx
    group: devopstest
spec:
  ports:
    - name: devops-nginx
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: devopstest
    container: devops-nginx
    group: devopstest
  sessionAffinity: None
