kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-nginx-deployment
  namespace: ks-devops-test
  labels:
    app: devopstest
    container: devops-nginx
    group: devopstest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopstest
      container: devops-nginx
      group: devopstest
  template:
    metadata:
      labels:
        app: devopstest
        container: devops-nginx
        group: devopstest
    spec:
      containers:
        - name: devops-nginx
          image: nginx:latest
          ports:
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2000Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
